import math # cini funkcije iz paketa dostupnim
print("Izracunavanje korena kvadratne jednacine")
print()
a, b, c = eval(input("Unesite koeficijente (a, b, c): "))
print(b * b - 4 * a * c)
root = math.sqrt(b * b - 4 * a * c)
root1 = (-b + root) / (2 * a)
root2 = (-b - root) / (2 * a)
print()
print("Resenja su:", root1, root2)